#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/haydn

PRODUCT_COPY_FILES += \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd \
    vendor/xiaomi/haydn/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.10.pmd \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_MACRO_V01.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_MACRO_V01.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_MACRO_V01_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_MACRO_V01_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_MACRO_V01_SN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_MACRO_V01_SN.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_MACRO_V01_SN_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_MACRO_V01_SN_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_UW_V01.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW_V01.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_UW_V01_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW_V01_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_UW_V01_SN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW_V01_SN.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_UW_V01_SN_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_UW_V01_SN_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_HD.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_HD.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_HD_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_HD_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_IZOOM.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_IZOOM.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_IZOOM_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_IZOOM_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_SN.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_SN.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/CFR_para_W_V01_SN_L.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/CFR_para_W_V01_SN_L.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/GpuKernelRepo.pb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/GpuKernelRepo.pb \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/LDC_FPC_TUNING_DATA.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_FPC_TUNING_DATA.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/LDC_FPC_TUNING_DATA_AI.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_FPC_TUNING_DATA_AI.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/LDC_PACKDATA_VENDORID_0x01.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_PACKDATA_VENDORID_0x01.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/LDC_PACKDATA_VENDORID_0x03.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_PACKDATA_VENDORID_0x03.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/LDC_PACKDATA_VENDORID_0x07.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/LDC_PACKDATA_VENDORID_0x07.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/MobNetv2TF_0.35_iter200000_zoom2.5x_h1500w2000.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/MobNetv2TF_0.35_iter200000_zoom2.5x_h1500w2000.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/ai_enhance.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ai_enhance.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/aivsParams.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/aivsParams.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/bokehParams.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/bokehParams.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/cache \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/camxoverridesettingsOfPro.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettingsOfPro.txt \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.fake:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.fake \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.golden \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.pro.fake:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.pro.fake \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/com.xiaomi.dcal.wu.pro.golden:$(TARGET_COPY_OUT_VENDOR)/etc/camera/com.xiaomi.dcal.wu.pro.golden \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/deblur_chess_gpu.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_chess_gpu.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/deblur_nonchess_gpu.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_nonchess_gpu.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/deblur_txt_gpu.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_txt_gpu.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/deblur_wood_gpu.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/deblur_wood_gpu.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/det_quantize.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/det_quantize.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/eisoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eisoverridesettings.txt \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/ellc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/ellc.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/fusion_models/fusion_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fusion_models/fusion_cache \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/fusion_models/fusion_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fusion_models/fusion_model \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/fusion_models/fusion_policy:$(TARGET_COPY_OUT_VENDOR)/etc/camera/fusion_models/fusion_policy \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/mibokeh_855_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_855_opencl.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/mibokeh_855_parameter.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/mibokeh_855_parameter.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model1.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model1.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model2.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model2.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model3.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model3.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model4.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model4.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model_ai_dxo.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_ai_dxo.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model_back.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_back.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model_front.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model_front_mibokeh_video.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_front_mibokeh_video.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/model_glass.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/model_glass.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/person_det_dsp.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/person_det_dsp.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/person_reid_gpu.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/person_reid_gpu.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/preview_bokeh_params.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/preview_bokeh_params.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/pureShot_parameter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/pureShot_parameter.xml \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/reid_float.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/reid_float.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/sceneDetection.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sceneDetection.xml \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/seg_quantized.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/camera/seg_quantized.dlc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/siq_ocl_cache:$(TARGET_COPY_OUT_VENDOR)/etc/camera/siq_ocl_cache \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/sr_params.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sr_params.xml \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/superiq_model:$(TARGET_COPY_OUT_VENDOR)/etc/camera/superiq_model \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/dualbokehjpegsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/dualbokehjpegsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/dualbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/dualbokehsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/frontbokehsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontbokehsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/frontsinglesnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsinglesnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/frontsupernightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsupernightsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/frontsupernightsnapshotjpeg.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/frontsupernightsnapshotjpeg.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/manualsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/manualsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/miviinfo.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/miviinfo.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/mivisettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/mivisettings.txt \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/normalsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/normalsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/rearsupernightsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/rearsupernightsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/satsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/satsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/superhdsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/superhdsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/thirdpartydualbokehyuvsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/thirdpartydualbokehyuvsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/thirdpartyjpegsnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/thirdpartyjpegsnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/camera/xiaomi/thirdpartysnapshot.json:$(TARGET_COPY_OUT_VENDOR)/etc/camera/xiaomi/thirdpartysnapshot.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/xiaomi/haydn/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/ltm_config_xiaomi_38_08_0a_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ltm_config_xiaomi_38_08_0a_cmd_mode_dsc_dsi_panel.xml \
    vendor/xiaomi/haydn/proprietary/vendor/etc/mdss_dsi_k11_38_08_0a_dsc_cmd_mi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mdss_dsi_k11_38_08_0a_dsc_cmd_mi.xml \
    vendor/xiaomi/haydn/proprietary/vendor/etc/qdcm_calib_data_xiaomi_38_08_0a_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_xiaomi_38_08_0a_cmd_mode_dsc_dsi_panel.xml \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmp285_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/bu27030_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bu27030_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/bu27030_0_back.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bu27030_0_back.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_ak991x_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_bmp285_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_bu27030_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_bu27030_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_bu27030_0_back.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_bu27030_0_back.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_bu52053nvx_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_default_sensors.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_dynamic_sensors.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_irq.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_lsm6dso_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_lsm6dst_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_lsm6dst_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_lsm6dst_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_lsm6dst_1.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_power_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_sx932x_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_sx932x_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_sx932x_1.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_tcs3408.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_tcs3408.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_tcs3701.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_tcs3701.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_tmd3719.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_tmd3719.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sm8350_vl53l1_tof_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sm8350_vl53l1_tof_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_aod.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aod.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_dbtap.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dbtap.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_nonui.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_nonui.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_sar_algo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_sar_algo.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_sar_algo_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_sar_algo_1.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sx932x_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/sx932x_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sx932x_1.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/tcs3408.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tcs3408.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/tcs3701.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tcs3701.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/tmd3719.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd3719.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/config/vl53l1_tof_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/vl53l1_tof_0.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/judge_calibrated.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/judge_calibrated.json \
    vendor/xiaomi/haydn/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-class0.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-camera.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-class0.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-mgame.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-navigation.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-nolimits.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-normal.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-phone.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-tgame.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-india-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-india-video.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-map-india.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map-india.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-map.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-mgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-mgame.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-navigation.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-nolimits.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-nolimits.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-normal.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-per-camera.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-camera.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-per-class0.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-class0.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-per-navigation.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-navigation.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-per-normal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-normal.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-per-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-per-video.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-phone.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-phone.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-region-map.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-region-map.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-tgame.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-tgame.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermal-video.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-video.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/thermald-devices.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermald-devices.conf \
    vendor/xiaomi/haydn/proprietary/vendor/etc/vibrator/effect_0.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_0.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/vibrator/effect_1.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_1.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/vibrator/effect_2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_2.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/vibrator/effect_3.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_3.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/vibrator/effect_4.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_4.bin \
    vendor/xiaomi/haydn/proprietary/vendor/etc/vibrator/effect_5.bin:$(TARGET_COPY_OUT_VENDOR)/etc/vibrator/effect_5.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_gmu.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_sqe.fw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.b00 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.b01 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.b02 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.elf \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/a660_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.mdt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag-revb2.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag-revb2.wmfw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag-z-RCV-revb2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag-z-RCV-revb2.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag-z-revb2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag-z-revb2.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag-z-revb2.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag-z-revb2.wmfw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag-z.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag-z.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag-z.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag-z.wmfw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-diag.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-diag.wmfw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-RCV-revb2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-RCV-revb2.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-RCV.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-RCV.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-revb2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-revb2.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot-revb2.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot-revb2.wmfw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/cs35l41-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l41-dsp1-spk-prot.wmfw \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b00 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b01 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b02 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b03 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b04 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b05 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b06 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b07 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b08 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b09 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b10 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b11 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b12 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b13 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b14 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b15 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b16 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b17 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b18 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.b19 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.mbn \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass-lt.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass-lt.mdt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/focaltech_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/focaltech_ts_ht_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_ht_fw.bin \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/rcv_voice_delta.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/rcv_voice_delta.txt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/spk1_playback_delta.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1_playback_delta.txt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/spk1_voice_delta.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk1_voice_delta.txt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/spk2_playback_delta.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2_playback_delta.txt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/spk2_voice_delta.txt:$(TARGET_COPY_OUT_VENDOR)/firmware/spk2_voice_delta.txt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b00 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b01 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b02 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b03 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b04 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b05 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b06 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b07 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b08 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b09 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b10 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b11 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b12 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b13 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b14 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b15 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b16 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b17 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b18 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.b19 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.mbn \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v.mdt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_2v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_2v_unsigned.mbn \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b00 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b01 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b02 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b03 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b04 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b05 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b06 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b07 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b08 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b09 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b10 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b11 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b12 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b13 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b14 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b15 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b16 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b17 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b18 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b19 \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mdt \
    vendor/xiaomi/haydn/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.sensormodule.haydn_ofilm_imx355_ultra.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.haydn_ofilm_imx355_ultra.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.sensormodule.haydn_sunny_imx686_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.haydn_sunny_imx686_wide.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.sensormodule.haydn_sunny_s5k3t2_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.haydn_sunny_s5k3t2_front.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.sensormodule.haydn_sunny_s5k5e9yx04_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.haydn_sunny_s5k5e9yx04_macro.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.sensormodule.haydn_sunny_s5khm2_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.haydn_sunny_s5khm2_wide.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.tuned.haydn_ofilm_imx355_ultra.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.haydn_ofilm_imx355_ultra.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.tuned.haydn_sunny_imx686_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.haydn_sunny_imx686_wide.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.tuned.haydn_sunny_s5k3t2_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.haydn_sunny_s5k3t2_front.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.tuned.haydn_sunny_s5k5e9yx04_macro.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.haydn_sunny_s5k5e9yx04_macro.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/com.qti.tuned.haydn_sunny_s5khm2_wide.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.haydn_sunny_s5khm2_wide.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/xiaomi/haydn/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/xiaomi/haydn/proprietary/vendor/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/libnfc-nxp_RF.conf

PRODUCT_PACKAGES += \
    audio.primary.lahaina \
    liba2dpoffload \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadm \
    libaudcal \
    libaudio_log_utils \
    libaudiocloudctrl \
    libaudioparsers \
    libaudioroute_ext \
    libbatterylistener \
    libfcsam \
    libhdmiedid \
    libhdmipassthru \
    libhfp \
    libqtigef \
    libresampler \
    libsndmonitor \
    libssrec \
    HDR10plus \
    com.qti.eeprom.haydn_ofilm_imx355_bl24s64_ultra_eeprom \
    com.qti.eeprom.haydn_sunny_imx686_gt24p128e_wide_eeprom \
    com.qti.eeprom.haydn_sunny_s5k3t2_p24c64f_front_eeprom \
    com.qti.eeprom.haydn_sunny_s5k5e9yx04_p24c64f_macro_eeprom \
    com.qti.eeprom.haydn_sunny_s5khm2_gt24p128e_wide_eeprom \
    com.qti.sensor.haydn_ofilm_imx355_ultra \
    com.qti.sensor.haydn_sunny_imx686_wide \
    com.qti.sensor.haydn_sunny_s5k3t2_front \
    com.qti.sensor.haydn_sunny_s5k5e9yx04_macro \
    com.qti.sensor.haydn_sunny_s5khm2_wide \
    com.mi.node.AIIE \
    com.mi.node.aiasd \
    com.mi.node.bodyslim \
    com.mi.node.distortioncorrection \
    com.mi.node.hdr \
    com.mi.node.mimovie \
    com.mi.node.mipitounpacketraw \
    com.mi.node.pureShot \
    com.mi.node.realtimebokeh \
    com.mi.node.rearvideo \
    com.mi.node.skinbeautifier \
    com.mi.node.superiq \
    com.mi.node.superlowlightraw \
    com.mi.node.videobokeh \
    com.mi.node.videonight \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gpu \
    com.qti.node.hdr10plushist \
    com.qti.node.hdr10plusmeta \
    com.qti.node.ldc \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.eis \
    com.vidhance.node.ica \
    com.vidhance.stats.aec_dmbr \
    com.xiaomi.node.mibokeh \
    com.xiaomi.node.mifilter \
    com.xiaomi.node.misegment \
    com.xiaomi.node.smooth_transition \
    com.xiaomi.node.tracker \
    libdepthmapwrapper_secure \
    com.qcom.plugin.gpu \
    com.qcom.plugin.jpegencode \
    com.qcom.plugin.offlinepostproc \
    com.xiaomi.plugin.bodyslim \
    com.xiaomi.plugin.capbokeh \
    com.xiaomi.plugin.dc \
    com.xiaomi.plugin.depurple \
    com.xiaomi.plugin.ellc \
    com.xiaomi.plugin.fusion \
    com.xiaomi.plugin.hdr \
    com.xiaomi.plugin.ldc \
    com.xiaomi.plugin.memcpy \
    com.xiaomi.plugin.miaideblur \
    com.xiaomi.plugin.miaiie \
    com.xiaomi.plugin.mibokeh \
    com.xiaomi.plugin.misegment \
    com.xiaomi.plugin.rearsupernight \
    com.xiaomi.plugin.sigframe \
    com.xiaomi.plugin.skinbeautifier \
    com.xiaomi.plugin.sr \
    com.xiaomi.plugin.supermoon \
    com.xiaomi.plugin.supernight \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.parallelVTCam \
    com.qti.feature2.pureShot \
    com.qti.feature2.pureShotPre \
    com.qti.feature2.qcfa \
    com.qti.feature2.qllimagedump \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rawsuperiq \
    com.qti.feature2.rawsupernight \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.settings.kamorta \
    com.qti.settings.mannar \
    com.qti.settings.sdm865 \
    com.qti.settings.sm8350 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    camera.xiaomi \
    com.qti.chi.override \
    fingerprint.fpc.lahaina \
    libAF \
    libBlinkStub \
    libFlickerDet \
    libI420colorconvert \
    libQnnHtpStub \
    libSNPE \
    lib_sr_models \
    libaidenoiser \
    libalAILDC \
    libalCFR \
    libalLDC \
    libalhLDC \
    libanc_dc_base \
    libanc_hdr \
    libancbase \
    libarcsoft_beautyshot \
    libarcsoft_bodyslim \
    libarcsoft_distortion_correction \
    libarcsoft_dual_sat \
    libarcsoft_dual_zoomtranslator \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdrplus_hvx_stub \
    libarcsoft_portrait_lighting \
    libarcsoft_portrait_lighting_c \
    libarcsoft_super_night_raw \
    libarcsoft_triple_sat \
    libarcsoft_triple_zoomtranslator \
    libbitmlengine \
    libblink \
    libc++_shared \
    libcamera_dirty \
    libcamera_nn_stub \
    libcamera_scene \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libcom.xiaomi.debug \
    libcom.xiaomi.grallocutils \
    libcom.xiaomi.metadatautils \
    libcom.xiaomi.pluginutils \
    libcvface_api \
    libdualcam_optical_zoom_control \
    libdualcam_video_optical_zoom \
    libellc \
    libfocus \
    libhdrdynamic \
    libhdrdynamicootf \
    libhexagon_controller \
    libipebpsstriping \
    libjpege \
    libmctfengine_stub \
    libmiai_deblur \
    libmiai_portraitsupernight \
    libmialgo_ai_vision \
    libmialgo_basic \
    libmialgo_ie_capture \
    libmialgo_ie_preview \
    libmialgo_image_colourkeeping \
    libmialgo_pureShot \
    libmialgo_rfs \
    libmialgo_sd \
    libmialgo_utils \
    libmialgo_video_colourkeeping \
    libmialgo_video_enhance \
    libmialgo_video_seg \
    libmialgo_vn_clk \
    libmialgoengine \
    libmibokeh_845_video \
    libmibokeh_855 \
    libmibokeh_mask_dsp \
    libmiphone_preview_bokeh \
    libmm-color-convertor \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmpbase \
    libnanopb \
    libnotifyaudiohal \
    libofflinedump \
    libofflinelog \
    libopencv \
    libopestriping \
    libos \
    libqll10 \
    libqllengine \
    librelight_only \
    libremosaic_wrapper \
    libremosaiclib \
    libsdk_sr \
    libsensorcal \
    libsensorslog \
    libsnpe_htp \
    libsns_api \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsns_registry_skel \
    libsnsapi \
    libsnsdiaglog \
    libssc \
    libssc_default_listener \
    libssccalapi \
    libsupermoon \
    libswregistrationalgo \
    libsynx \
    libtfestriping \
    libthreadutils \
    libtriplecam_optical_zoom_control \
    libtriplecam_video_optical_zoom \
    libultrasound \
    libvideoBokeh \
    libvideofilter_only \
    libvidhance \
    libwa_opticalzoom_fusion \
    libxmi_hdr_checker \
    libxmi_high_dynamic_range \
    sensors.mius.proximity \
    sensors.ssc \
    sensors.touch.detect \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.xiaomi.hardware.cameraperf@1.0-impl \
    vendor.xiaomi.hardware.cameraperf@1.0 \
    vendor.xiaomi.hardware.campostproc@1.0-service-impl \
    vendor.xiaomi.hardware.campostproc@1.0 \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDADV_Encoder_so \
    vendor_lib_rfsa_adsp_capi_v2_aptX_CLHDAD_Speech_Decoder_so \
    vendor_lib_rfsa_adsp_capi_v2_cirrus_sp_so \
    vendor_lib_rfsa_adsp_capi_v2_dap_cpdp_so \
    vendor_lib_rfsa_adsp_hrtf5c_bin \
    vendor_lib_rfsa_adsp_libMIAIHDR_skel_so \
    vendor_lib_rfsa_adsp_libQ6MSFR_manager_skel_so \
    vendor_lib_rfsa_adsp_libQnnHtpAltPrepSkel_so \
    vendor_lib_rfsa_adsp_libQnnHtpSkel_so \
    vendor_lib_rfsa_adsp_libVppAisQnnHtp_so \
    vendor_lib_rfsa_adsp_libVppQnnHtp_so \
    vendor_lib_rfsa_adsp_libadsp_jpege_skel_so \
    vendor_lib_rfsa_adsp_libapps_mem_heap_so \
    vendor_lib_rfsa_adsp_libarcsoft_hdrplus_hvx_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_skel_so \
    vendor_lib_rfsa_adsp_libbitml_nsp_v2_skel_so \
    vendor_lib_rfsa_adsp_libcamera_nn_skel_so \
    vendor_lib_rfsa_adsp_libcvpdsp_2_1_so \
    vendor_lib_rfsa_adsp_libdspCV_skel_so \
    vendor_lib_rfsa_adsp_libdsp_streamer_binning_so \
    vendor_lib_rfsa_adsp_libfastcvadsp_so \
    vendor_lib_rfsa_adsp_libfastcvdsp_skel_so \
    vendor_lib_rfsa_adsp_libhap_blink_skel_so \
    vendor_lib_rfsa_adsp_libhdr_skel_so \
    vendor_lib_rfsa_adsp_libmctfengine_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_basic_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_mfnr_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_rfs_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libmialgo_sfnr_cdsp_skel_so \
    vendor_lib_rfsa_adsp_libscveObjectSegmentation_skel_so \
    vendor_lib_rfsa_adsp_libscveT2T_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_htp_v65_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_htp_v66_skel_so \
    vendor_lib_rfsa_adsp_libsnpe_htp_v68_skel_so \
    vendor_lib_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib_rfsa_adsp_libsns_low_lat_stream_skel_so \
    vendor_lib_rfsa_adsp_libsuper_res_networks_so \
    vendor_lib_rfsa_adsp_libvpp_ais_networks_so \
    vendor_lib_rfsa_adsp_libvpt_action_recognition_so \
    vendor_lib_rfsa_adsp_misound_karaoke_res_bin \
    vendor_lib_rfsa_adsp_misound_karaokemix_res_bin \
    vendor_lib_rfsa_adsp_misound_res_headphone_bin \
    vendor_lib_rfsa_adsp_misound_res_spk_bin \
    batterysecret \
    init.qcom.sensors \
    sensors.qti \
    sscrpcd
